#!/usr/bin/python3

from pythoncraft import networking
import sys

if __name__ == "__main__":
    if len(sys.argv) >= 2:
        if sys.argv[1] == "-d":
            s = networking.Server()
        else:
            s = networking.Client( message = sys.argv[1:] )
    else:
        print( "That's not how you use this program!!" )
